name = "Falopacraft"
author = "Sephiroth1993"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a687a1b1d8071367a7d5cb9952326fa53e917394a908e816220a55a39ddc3e53"

[versions]
forge = "47.4.20"
minecraft = "1.20.1"
