name = "Falopacraft"
author = "Sephiroth1993"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0b9f1ddd1ce36914baa12d594721c96c72d17a536acd26268229e8e852da9196"

[versions]
forge = "47.4.16"
minecraft = "1.20.1"
